obj-$(CONFIG_FINGERPRINT_GOODIX_GF3208_MIDO) += goodix_mido/
obj-$(CONFIG_FINGERPRINT_FPC1020_MIDO) += fpc_mido/
obj-$(CONFIG_FINGERPRINT_GOODIX_GF3208_TISSOT) += goodix_tissot/
obj-$(CONFIG_FINGERPRINT_FPC1020_TISSOT) += fpc_tissot/
#
# Makefile for the fingerprint drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_FINGERPRINT_FPC1020_TA)	+= fpc1020_tee.o
